server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calendrier?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

