# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Njc0MzdhYTk1NTQ4YmFkYjZiOWIzMmQyZTNlN2ZlOGMwOTFlYWE5MWM2N2U1MGM4ZWY1YWE1OTMwYmY4MmI1NjQwYTZhNjczMWEyMmI5ZDNmMTk4NDYwZmMxZWVhYWI1YzZjYjJkM2M2NGU1ODE1YmYzMjEzYTg3NDVlNGE0ODA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
